# Generated by Django 4.0.5 on 2022-06-13 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=25)),
                ('Password', models.CharField(max_length=15)),
                ('IsActive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'master',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Shop_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop_Types', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'shop_types',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOS', models.DateField(auto_created=True, default='2020-01-01')),
                ('DOB', models.DateField(auto_created=True, default='2020-01-01')),
                ('ProfileImage', models.FileField(default='images/user.png', upload_to='images/users')),
                ('First_Name', models.CharField(default='', max_length=25)),
                ('Last_Name', models.CharField(default='', max_length=25)),
                ('Gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10)),
                ('ShopImage', models.FileField(default='images/shop.png', upload_to='images/shops')),
                ('OwnerName', models.CharField(default='', max_length=25)),
                ('ShopName', models.CharField(default='', max_length=25)),
                ('Del_Status', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=10)),
                ('DOJ', models.DateField(auto_now=True)),
                ('Contact', models.CharField(default='', max_length=12)),
                ('H_S_no', models.CharField(default='', max_length=25)),
                ('Complex_Name', models.CharField(default='', max_length=25)),
                ('Nr_Landmark', models.CharField(default='', max_length=25)),
                ('Country', models.CharField(default='', max_length=25)),
                ('City', models.CharField(default='', max_length=25)),
                ('State', models.CharField(default='', max_length=25)),
                ('Pincode', models.CharField(default='', max_length=25)),
                ('Address', models.TextField(default='', max_length=250)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoApp.master')),
                ('Shop_Types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoApp.shop_types')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoApp.role'),
        ),
    ]
