# Generated by Django 4.0.5 on 2022-06-13 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0002_alter_shop_types_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Shop_Types',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='demoApp.shop_types'),
        ),
    ]
