# Generated by Django 4.0.5 on 2022-06-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0004_remove_profile_complex_name_remove_profile_h_s_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ShopImage',
        ),
    ]
