# Generated by Django 4.0.5 on 2022-06-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0005_remove_profile_shopimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='Email',
            field=models.EmailField(max_length=25, unique=True),
        ),
    ]
