# Generated by Django 4.0.5 on 2022-06-16 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0006_alter_master_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Del_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Del_Status', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'del_Status',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='Del_Status',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='demoApp.del_status'),
        ),
    ]
