# Generated by Django 4.0.5 on 2022-06-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0007_del_status_alter_profile_del_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Del_Status',
        ),
        migrations.DeleteModel(
            name='Del_Status',
        ),
    ]
