# Generated by Django 4.0.5 on 2022-06-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0009_del_status_profile_del_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ProfileImage',
            field=models.FileField(default='', upload_to='images/users'),
        ),
    ]
