# Generated by Django 4.0.5 on 2022-06-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0010_alter_profile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOJ',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
