# Generated by Django 4.0.5 on 2022-06-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0011_alter_profile_doj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOJ',
            field=models.DateField(auto_now=True),
        ),
    ]
